---
title: "Charlotte Traffic Stop"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard); library(tidyverse); library(ggridges)

months <- c("Jan","Feb","Mar",
            "Apr","May","Jun",
            "Jul","Aug","Sep",
            "Oct","Nov","Dec")

# read in and clean up fields
df <- read_csv("./data/cleaned-stops.csv") %>%
  mutate(Month = forcats::fct_relevel(Month, months),
         Year = as.character(Year),
         DriverRace = case_when(
           Driver_Ethnicity == "Hispanic" ~ "Hispanic",
           Driver_Race %in% c("White", "Black") ~ Driver_Race,
           TRUE ~ "Other"
         ),
         OfficerRace = case_when(
           Officer_Race == "Hispanic/Latino" ~ "Hispanic",
           Officer_Race == "Black/African American" ~ "Black",
           Officer_Race == "White" ~ "White",
           TRUE ~ "Other")
  ) %>%
  select(-Driver_Ethnicity, -Driver_Race, -Officer_Race)
```

Inputs {.sidebar}
-------------------------------------

```{r}
selectInput('reason', 'Reason For Stop', c(All = ".", unique(df$Reason_for_Stop)))
br()
sliderInput('fontSize','Adjust Font Size', min = 4, max = 20, value = 12)
br()
sliderInput('scale', 'ggridge Scale', min = 0.1, max = 5, value = 3.5)
sliderInput('ageRange', 'ggridge Age Scale', min = 0, max = 110, value = c(10,70))
```

Row {.tabset .tabset-fade}
-------------------------------------

### Reason for Stops

```{r}
renderPlot({
  # yield full df if All selected; or filter
  if(input$reason == "."){
    z <- df
  }
  else {
    z <- filter(df, Reason_for_Stop == input$reason)
  }
  
  z %>%
    group_by(Month, Year, Reason_for_Stop) %>%
    summarise(Count = n()) %>%
    ggplot(aes(x = Month, y = Count, fill = Reason_for_Stop)) +
    geom_col() +
    facet_grid(Year~.) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1),
          text = element_text(size=input$fontSize),
          legend.position = "bottom")
})
```

### Driver & Officer Race

The chart rows represent the race of the Officer; chart columns represent the race of the driver.

```{r}
renderPlot({
  # yield full df if All selected; or filter
  if(input$reason == "."){
    z <- df
  }
  else {
    z <- filter(df, Reason_for_Stop == input$reason)
  }
  
  z %>%
    group_by(Month, Year, OfficerRace, DriverRace) %>%
    summarise(Count = n()) %>%
    ggplot(aes(x = Month, y = Count, color = Year, group = Year)) +
    geom_point() + 
    geom_line() +
    facet_grid(OfficerRace~DriverRace) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1),
          text = element_text(size=input$fontSize))
})
```

### Age & Result of Stop

```{r}
renderPlot({
    # yield full df if All selected; or filter
  if(input$reason == "."){
    z <- df
  }
  else {
    z <- filter(df, Reason_for_Stop == input$reason)
  }

  z %>%
    ggplot(aes(x = Driver_Age, y = Result_of_Stop, fill = Result_of_Stop)) +
    geom_density_ridges(alpha = 0.4, scale = input$scale) +
    theme(text = element_text(size=input$fontSize),
          legend.position = "none") +
    xlim(input$ageRange[1], input$ageRange[2])
})
```